---
title: "Exploring"
author: "Elizabeth Delmelle"
date: "2023-09-12"
output: 
  html_document:
    theme: united
    toc: true
    toc_float: true
    code_download: true
---


```{r setup, include = FALSE}
  knitr::opts_chunk$set(
    echo = FALSE,
    warning = FALSE,
    message = FALSE,
    out.width = '100%',
    fig.retina = 3,
    fig.path = ("figures/")
  )
```


```{r organize directories, include = FALSE}

dir.create("figures")
dir.create("codes")

```




```{r libraries, include = FALSE}
library(tidycensus)
library(dplyr)
library(tidyverse)
library(tidyr)
```

# An Introduction to Tidy Census

## Getting Data

This is the TidyCensus package developed by **Kyle Walker** from *TCU*


```{r getdata}
total_population_10 <- get_decennial(
  geography = "state", 
  variables = "P001001",
  year = 2010
)


ga_wide <- get_acs(
  geography = "county",
  state = "Georgia",
  variables = c(medinc = "B19013_001",
                medage = "B01002_001"),
  output = "wide",
  year = 2020
)
```


This is a histogram of something very important.
```{r histogram, fig.cap= "Histogram of medicE"}

ggplot(ga_wide, aes(x = medincE)) + 
  geom_histogram()

```
```{r boxplot}
ggplot(ga_wide, aes(y = medincE)) + 
  geom_boxplot()
```

